### PR TITLE
Added multiple API calls and helper functions

### PR DESCRIPTION
**Pull request by bdevoe**
Saw some activity on this repo and realized I've been meaning to send a pull request for quite awhile. I've added some more API calls and helper functions since the last request. Most of this in production within our department and should be good to go; the only exception is the update functionality of the sync_table function, which needs some work.

I pulled your latest changes (switch to jose package for OAuth) into this dev branch first as well - this should not mess up anything I've written but I have yet to fully test your changes.

### CODE REVIEW

**Comment by arestrom** [comment]
Thanks Bill, much appreciated. I should be able to take a look on Monday.

**Comment by bdevoe** [comment]
Yeah no rush on my end, I don't think I've worked on this since last June - sorry it's all as one giant pull request, it probably would have been easier as incremental requests.

**Comment by arestrom** [comment]
Looks great. Given current workload, I'm thinking of incorporating these in
chunks as I get time to write tests and get familiar with the functions.
Especially the sync functionality. Much appreciated. This should come in
handy for out work as well.

**Comment by arestrom** [comment]
Thanks for this PR. I've incorporated most of the new functions into the latest release. I'm hoping to find time to play with the rest soon. Since I needed to parse this submission out into successive chunks I'm closing this PR. Much appreciated.

**Comment by bdevoe** [comment]
No problem, thanks!

**Pull request closed without merging**
